name: ce-binary-classification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - calibrated-explanations==0.2.3
    - lime==0.2.0.1
    - shap==0.44.0
    - xgboost
    - seaborn
    - scipy
    - joblib
    - matplotlib
    - ucimlrepo
